### ISSUE TITLE
Mandou muito...

### ISSUE THREAD

**Issue by gabrieldarezzo** [hc3/headfirstStudyBook#1]
Olhei meio que correndo... mas na boa...
Animal.
Caso queira deixar o link de 'como'executar/rodar um JavaScript' no meu repo tem um passo a passo ilustrado com fotos.

https://github.com/gabrieldarezzo/helpjs-ravi

Vou linkar seu repo tmb

**Comment by hc3** [comment]
muito obrigado. vou ver seu repo!
